### ISSUE TITLE
Minor issue

### ISSUE THREAD

**Issue by UnknownBallin** [SuperStulle007/UltraCapes#2]
UnknownBallin joined the game
[16:01:23] [Server thread/CRITICAL]: Error: "Call to undefined function UltraCapes\imagecreatefrompng()" (EXCEPTION) in "plugins/UltraCapes_dev-10.phar/src/UltraCapes/Main" at line 78

**Comment by SuperStulle007** [comment]
When does this error occur?

**Comment by UnknownBallin** [comment]
Any time I attempt to choose a cape unfortunately

**Comment by SuperStulle007** [comment]
Should be fixed

**Comment by UnknownBallin** [comment]
Same error still happens, this is the second plugin I've had this exact error with, so it must be something on my end. The issue doesn't seem to happen to anyone else, so my apologies for the issue!

**Comment by usser1976** [comment]
When creating the config, only "enderman.png" is loaded.  You have to insert the other .png manually.  Could that be the mistake?  Look in the folder at plugin data

**Comment by SuperStulle007** [comment]
With the latest Build all Capes are loading, when the plugin is loading

**Comment by SuperStulle007** [comment]
Should be fixed with the latest build!

**Comment by SuperStulle007** [comment]
If this Error comes again you have to delete the UltraCapes Folder in the plugins_data folder.

**Comment by TheWalkingDrift** [comment]
@UnknownBallin you must to enable gd
